<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DoctorSeeder extends Seeder
{
    public function run()
    {

        DB::table('doctors')->insert([
            [
                'user_id' => 14,
                // 'full_name' => 'd1',
                'date_of_birth' => '1980-05-15',
                'gender' => 'Male',
                'profile_photo' => 'https://example.com/photos/john_doe.jpg',
                'nationality' => 'American',
                'languages_spoken' => 'English, Spanish',
                'primary_phone_number' => '1234567890',
                'home_address' => '123 Elm Street, New York, USA',
                'clinic_hospital_address' => 'XYZ Hospital, New York',
                'specialization' => 'Cardiology',
                'license_number' => 'LIC123456',
                'years_of_experience' => 15,
                'medical_degrees' => 'MD',
                'board_certifications' => 'American Board of Internal Medicine',
                'university_college_attended' => 'Harvard Medical School',
                'medical_council_registration_number' => 'MC987654',
                'professional_memberships' => 'American Medical Association',
                'research_publications' => 'Study on Heart Diseases, 2020',
                'current_hospital_clinic' => 'XYZ Hospital',
                'previous_workplaces' => 'ABC Medical Center, DEF Hospital',
                'internship_residency_details' => 'XYZ Medical Residency Program',
                'consultation_hours' => 'Mon-Fri: 9 AM - 5 PM',
                'online_consultation_availability' => true,
                'walk_in_availability' => false,
                'appointment_booking_required' => true,
                // 'max_patients_per_day' => 20,
                'time_of_one_appointment' => 30,
                'surgical_expertise' => 'Cardiac Surgery',
                'treatment_approach' => 'Conservative & Surgical',
                'consultation_fees' => 200.00,
                'payment_methods_accepted' => 'Cash, Card, Online Payments',
                'average_rating' => 4.7,
                // 'patient_reviews' => 'Excellent doctor with great expertise.',
                'awards_recognitions' => 'Best Cardiologist Award 2019',
                'website_url' => 'https://drjohndoe.com',
                'linkedin_profile' => 'https://linkedin.com/in/drjohndoe',
                'twitter_x_handle' => '@drjohndoe',
                'youtube_channel' => 'https://youtube.com/drjohndoe',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 15,
                // 'full_name' => 'd2',
                'date_of_birth' => '1975-11-20',
                'gender' => 'female',
                'profile_photo' => 'https://example.com/photos/jane_smith.jpg',
                'nationality' => 'Canadian',
                'languages_spoken' => 'English, French',
                'primary_phone_number' => '9876543210',
                'home_address' => '456 Oak Street, Toronto, Canada',
                'clinic_hospital_address' => 'ABC Clinic, Toronto',
                'specialization' => 'Neurology',
                'license_number' => 'LIC654321',
                'years_of_experience' => 20,
                'medical_degrees' => 'MD',
                'board_certifications' => 'Canadian Board of Neurology',
                'university_college_attended' => 'University of Toronto',
                'medical_council_registration_number' => 'MC123789',
                'professional_memberships' => 'Canadian Neurology Association',
                'research_publications' => 'Neurological Disorders Study, 2021',
                'current_hospital_clinic' => 'ABC Clinic',
                'previous_workplaces' => 'XYZ Neurology Institute',
                'internship_residency_details' => 'Toronto General Residency Program',
                'consultation_hours' => 'Tue-Thu: 10 AM - 4 PM',
                'online_consultation_availability' => true,
                'walk_in_availability' => true,
                'appointment_booking_required' => false,
                // 'max_patients_per_day' => 15,
                'time_of_one_appointment' => 60,
                'surgical_expertise' => 'Brain Surgery',
                'treatment_approach' => 'Alternative & Traditional Medicine',
                'consultation_fees' => 250.00,
                'payment_methods_accepted' => 'Cash, Credit Card',
                'average_rating' => 4.8,
                // 'patient_reviews' => 'Very knowledgeable and caring doctor.',
                'awards_recognitions' => 'Neurologist of the Year 2021',
                'website_url' => 'https://drjanesmith.com',
                'linkedin_profile' => 'https://linkedin.com/in/drjanesmith',
                'twitter_x_handle' => '@drjanesmith',
                'youtube_channel' => 'https://youtube.com/drjanesmith',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
